### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by jasonpott** [KonstantinRyabov/dmtools#21]
Hi the dmtools package was the only package that I could identify that interfaced with the MEDDRA api. The functions were helpful to get me started with the API - thanks.

The functions did not include a mechanism to create a valid json submission. I've worked on this further and have uploaded some example functions to a repository readme. I don't know if you are planning to continue to work on the dmtools package and wondered whether you would be interested in incorporating them?

The addition of functions to create valid json may be a useful addition to your package.

The readme with my functions is here: https://github.com/jasonpott/meddra_api_R/blob/main/README.md

**Comment by KonstantinRyabov** [comment]
Hi, I'm glad my work helped you. I am not currently using meddra and have no plans to develop this functionality yet. But Maybe in the distant future, I will return to this))

**Comment by jasonpott** [comment]
No problem, many thanks
